# Generated by Django 5.1.3 on 2024-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow')], default='INFLOW', max_length=12, verbose_name='transaction type'),
        ),
    ]
